id: PE002FA9B
initial_creation_type: input
source_metadata:
  title: Vādanyāya
  language:
  - English
  - Sanskrit
  term: Sanskrit -- Śāstra -- Philosophy -- Buddhist
  data entry: Motoi Ono
  contribution to GRETIL: Motoi Ono
  initial normalization and conversion to legacy GRETIL formats: Reinhold Grünendahl
  normalization and conversion to TEI-conformant markup: Maximilian Mehner
created_at: '2022-03-09T15:13:02.707999'
last_modified_at: '2022-03-09T15:13:02.708012'
